### PR TITLE
memory allocation cleanups

### PR DESCRIPTION
**Pull request by stoeckmann**
Spotted some issues in libmaxminddb. These ones can be grouped into category "memory allocation".

### CODE REVIEW

**Comment by autarch** [comment]
The compiler does not like last commit (https://travis-ci.org/maxmind/libmaxminddb/jobs/99864912). Looks like maybe you need some extra parens? I don't have the C precedence table memorized, so maybe it's something else.

**Comment by oschwald** [comment]
The issue is that the conditionals are always true on a 64 bit platform and we have `-Werror` enabled for Travis.

**Comment by stoeckmann** [comment]
You both are really really quick with feedback, wow. :)

Yes, the issue was that the compiler dislikes checks that are always true. I fixed this with a preprocessor statements, basically what I did with OpenBSD code, too.

**Comment by oschwald** [comment]
This looks reasonable to me. I'll let @autarch merge.

**Comment by autarch** [comment]
@stoeckmann - I'll look at this on Monday when I'm at work.

**Comment by autarch** [comment]
I made a branch in the main repo with this change plus another to make the check a single macro. If it passes Travis I'll merge it. Thanks!

**Pull request closed without merging**
