### PR TITLE
Set PACKAGE_VERSION in header file for CMake

### PR DESCRIPTION
**Pull request by oschwald**
- Only set PACKAGE_VERSION on WIN32 if not set
- Define PACKAGE_VERSION in .in file for CMake

### CODE REVIEW

**Comment by bsergean** [comment]
I noticed that there was a value is set to 1.7.1, while ultimately it will be 1.7.2 after the release.

**Comment by bsergean** [comment]
Some CMake runs failed for some reason...

**Comment by bsergean** [comment]
```
/home/runner/work/libmaxminddb/libmaxminddb/t/version_t.c:6:21: error: ‘PACKAGE_VERSION’ undeclared (first use in this function); did you mean ‘MMDB_PACKAGE_VERSION’?
    6 |         is(version, PACKAGE_VERSION, "version is " PACKAGE_VERSION);
      |                     ^~~~~~~~~~~~~~~
```

That probably needs to become MMDB_PACKAGE_VERSION, like the compiler guessed.

**Comment by oschwald** [comment]
The release script updates the version numbers to match the `Changes.md`. It looks like the failed build is due to the last commit I pushed. I'll fix that.

**Review by bsergean — APPROVED** [review]
lgtm

**Comment by oschwald** [comment]
Thanks! In the end, I went with the changes from your PR. :slightly_smiling_face:

**Comment by bsergean** [comment]
That's funny :) / in any case thanks for looking at this.

It's good that we can stop using our fork, I noticed you have made a few releases recently, so not sure if this small change is worth a new one. I have started using tarballs from release for building when I can as this make it a bit faster, or it feels like it, since you don't need to clone a repo and fetch all the history attached with it.

**Review by FreeKitty — APPROVED** [review]

**Pull request merged**
